*-------------------------------------------------------
* Generated by nfCustEnvHelper.prg
* https://github.com/nfoxdev/customEnvHelper
*-------------------------------------------------------
* place here code to run for all projects
*
*

With _Screen

   * set project screen color
   Try
      cconfig  = Filetostr(Sys(2019))
      fc = Strextract(m.cconfig,"screenForeColor=","",1,1)
      bc = Strextract(m.cconfig,"screenBackColor=","",1,1)
      .ForeColor   = Evl(val(m.fc),.ForeColor)
      .BackColor   = Evl(val(m.bc),.BackColor)
   Catch
   Endtry

   .Caption   = Fullpath('')
   .FontName  = 'Consolas'
   .FontSize  = 12

  set status bar on

   Clear
   @ 2,5 Say Fullpath('') Font 'Ebrima',26
   ? ' '
   ? ' '
   ? 'Search Path: '
   ? '-'+Strtran(Set('path'),';','   -')
   ? 'dir *.*:'
   Dir *.*

Endwith


