*-------------------------------------------------------
* Generated by nfCustEnvHelper.prg
* https://github.com/nfoxdev/customEnvHelper
*-------------------------------------------------------
* place here code to run for all projects
*
*

set path to &&  path is saved in registry; make sure is not shared
set memowidth to int(wcols()*.9) && just a convenient setting




